kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: app-namespace
  name: pod-reader
rules:
- apiGroups: [""] # the core API group
  resources: ["pods"]
  verbs: ["get", "list"]